easy_admin:

   site_name: '<em style="font-size: 30px; color:#20B2AA;">Medical Achat </em>'

   user:
      display_name: true

   design:
      form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
      brand_color: '#00a6eb'
      menu:
         - {label: 'Gestion de ma boutique'}
         - label: 'Produits'
           children:
               - { entity: 'Produits', label: 'Liste des produits', icon: 'th-list' }
               - { entity: 'Produits', label: 'Ajouter un Produit', icon: 'plus', params: {action: 'new'}}
         - label: 'Categories'
           children:
               - { entity: 'Categories', label: 'Liste des Catégories', icon: 'th-list' }
               - { entity: 'Categories', label: 'Ajouter une catégorie', icon: 'plus', params: {action: 'new'}}
         - label: 'Sous_Categories'
           children:
               - { entity: 'SousCategories', label: 'Liste des Sous_Categorie', icon: 'th-list' }
               - { entity: 'SousCategories', label: 'Ajouter sous_catégorie', icon: 'plus', params: {action: 'new'}}
         - label: 'Utilisateurs'
           children:
               - { entity: 'Users', label: 'Liste des Utilisateurs', icon: 'user' }
               - { entity: 'Users', label: 'Ajouter un utilisateur', icon: 'plus', params: {action: 'new'}}
   formats:
        datetime: 'd/m/Y à H:i'
   entities:
      # List the entity class name you want to manage
      Produits:
         class: App\Entity\Produits
         list:
            actions:
               - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
               - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            fields:
               - id
               - reference
               - nom
               - { property: 'image', label: 'Image', type: 'image', base_path: '%app.path.produits_images%' }
               - prix
               - { property: 'categorie', label: 'Catégories'}
               - { property: 'sousCategories', label: 'Sous_Catégorie'}
               - stock
               - { property: 'created_at', label: 'Créé'}

      Categories:
         class: App\Entity\Categories
         list:
            actions:
               - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
               - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      SousCategories:
         class: App\Entity\SousCategories
         list:
            actions:
               - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
               - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      Users:
         class: App\Entity\Users
         list:
            actions:
               - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
               - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}